### ISSUE TITLE
Output resolution

### ISSUE THREAD

**Issue by sherifsas** [ac-freeman/davis-EDI-rs#15]
Hi! first of all, great work. I am interested in deblur using the aid of event camera. I have setup everything and built the project. Unfortunately, the resolution of the output video i corrupted can you please assist me with this issue ?

I used the dataset in the project ( dvSave-2022_05_17_14_48_18.aedat4)

![resullt](https://user-images.githubusercontent.com/20779302/221561199-93a52a1e-25a8-4c22-bb3b-2ef414216456.png)
)

**Comment by ac-freeman** [comment]
Hm. Did you generate the video with the `--write-video` option, or do it manually?

**Comment by sherifsas** [comment]
here is my Argos.toml

args_filename = ""
base_path = "/home/davis-EDI-rs/dataset"
#base_path = "/tmp"
mode = "file"
#mode = "socket"
#events_filename_0 = "dv-runtime.sock"
events_filename_0 = "dvSave-2022_05_17_14_48_18.aedat4"
events_filename_1 = "dv-runtime2.sock"
start_c = 0.30344322344322345
deblur_only = false
events_only = false
simulate_packet_latency = true
target_latency = 500.0
optimize_c = true
optimize_controller = false
show_display = false
show_blurred_display = false
output_fps = 10000
write_video = true

**Comment by ac-freeman** [comment]
Pull the latest changes and try it now. Writes to an .avi file directly, without the undefined behavior you encountered. I think it's slightly lossy, so let me know if that's a problem for you and I can see what else I can do.

**Comment by ac-freeman** [comment]
Can you email me the .avi file? acfreeman@cs.unc.edu

Also, what version of ffmpeg do you have installed?

**Comment by ac-freeman** [comment]
Gotcha. I've only tested this on Linux, so I can't vouch for how it works on Windows.
